#+TITLE: salv.el

#+begin_quote
*Salve*, v. t. & i.

To save, as a ship or goods, from the perils of the sea.

/--Webster, 1913/
#+end_quote

*Q:* /How does this package differ from other ones that automatically save buffers?/

*A:* Salve is a buffer-local minor mode, rather than being a global mode.  It is activated in buffers the user wants to be saved, rather than in all buffers (requiring the user to exclude ones that aren't to be saved).  It uses per-buffer idle timers, rather than a global timer.  It only runs a timer when a buffer is modified after being saved, rather than constantly.

Because of these characteristics, it's simple and lightweight.  To use, just, e.g. add ~salv-mode~ to a major mode hook.  Or, if you only want it activated in certain conditions, write a simple lambda to activate it when appropriate.  For example, the author uses:

#+begin_src elisp
  (add-hook 'org-mode-hook
            (lambda ()
              (when (and (buffer-file-name)
                         (file-in-directory-p (buffer-file-name) org-directory))
                (salv-mode 1))))
#+end_src
